### ISSUE TITLE
jekyll theme config not set for pages

### ISSUE THREAD

**Issue by scottnonnenberg** [seanode/seanode.github.io#4]
It seems that all entries are having trouble pulling down the theme... 
http://seanode.github.io/2016/01/15/feb-2016-hardware-management-and-debugging
http://seanode.github.io/2016/01/15/feb-2016-hardware-management-and-debugging

This works, on the front page http://seanode.github.io/assets/themes/twitter/css/style.css?body=1
This doesn't, on entry pages http://seanode.github.io/assets/themes//css/style.css?body=1

**Comment by ryan-roemer** [comment]
Ideas:

* [ ] Check if GH changed jekyll version.
* [ ] Locally test upgraded jekyll version.
